name = "contratos-iav-v4"
account_id = "0d0d6aaf107ae092f9fb5da06ddb338c"
main = "src/index.js"
compatibility_date = "2024-01-01"

[assets]
directory = "../frontend"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "contratos-iav-v4"
database_id = "84ae26a8-5bbc-4cdc-ad39-ead4c6bc7500"

[[r2_buckets]]
binding = "CHECKLIST_BACKUP"
bucket_name = "iav-checklist-backups"

[vars]
ADMIN_KEY = "framedock"
APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwv6J6Mh-y31LYGdLBasL0bFDOloosEaiaLJDXH-TIF2-A_VpFUbh14I9zHt43LEfY/exec"

[triggers]
crons = ["0 * * * *"]

[[routes]]
pattern = "contratos.inmueblesaudiovisuales.com/*"
zone_name = "inmueblesaudiovisuales.com"
